<a href="https://colab.research.google.com/github/PRAKRUTHI-20/daily-assignment/blob/main/day2assingment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Function to perform matrix multiplication
def matrix_multiply(A, B):
    return np.dot(A, B)

# Example matrices
A = np.array([[2, 2],
              [3, 3]])
B = np.array([[1, 5],
              [7, 8]])

# Perform multiplication
result = matrix_multiply(A, B)
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix Multiplication Result:\n", result)


Matrix A:
 [[2 2]
 [3 3]]
Matrix B:
 [[1 5]
 [7 8]]
Matrix Multiplication Result:
 [[16 26]
 [24 39]]


In [6]:
data = [5, 10, 15, 20, 25]


def min_max_scale(data):
    min_val = min(data)
    max_val = max(data)
    return [(x - min_val) / (max_val - min_val) for x in data]

scaled_data = min_max_scale(data)
print("Original Data:", data)
print("Min-Max Scaled Data:", scaled_data)


Original Data: [5, 10, 15, 20, 25]
Min-Max Scaled Data: [0.0, 0.25, 0.5, 0.75, 1.0]


In [7]:
def standardize(data):
    mean = sum(data) / len(data)
    std = (sum([(x - mean) ** 2 for x in data]) / len(data)) ** 0.5
    return [(x - mean) / std for x in data]

standardized_data = standardize(data)
print("Standardized Data:", standardized_data)


Standardized Data: [-1.414213562373095, -0.7071067811865475, 0.0, 0.7071067811865475, 1.414213562373095]
